export const monsters = {
	jeanne: {
		currentStars: 5,
		neededStars: 5,
		element: 'light', 
		highEle: 20,
		midEle: 10,
		lowEle: 0,
		highMagic: 15,
		midMagic: 5,
		lowMagic: 0,
		requires: ['kaz', 'lingling', 'harmonia', 'loren'],
		unawakenedName: 'Paladin',
		image: 'https://vignette.wikia.nocookie.net/summoners-war-sky-arena/images/f/ff/Paladin_%28Light%29_Icon.png/revision/latest/scale-to-width-down/85?cb=20170928142407'
	},
	sigmarus: {
		currentStars: 5,
		neededStars: 5,
		element: 'water', 
		highEle: 20,
		midEle: 10,
		lowEle: 0,
		highMagic: 15,
		midMagic: 5,
		lowMagic: 0,
		requires: ['arang', 'jojo', 'susano', 'mina'],
		unawakenedName: 'Phoenix',
		image: 'https://vignette.wikia.nocookie.net/summoners-war-sky-arena/images/3/33/Phoenix_%28Water%29_Icon.png/revision/latest/scale-to-width-down/85?cb=20141213080534'
	},
	katarina: {
		currentStars: 5,
		neededStars: 5,
		element: 'wind', 
		highEle: 20,
		midEle: 10,
		lowEle: 0,
		highMagic: 15,
		midMagic: 5,
		lowMagic: 0,
		requires: ['baretta', 'mikene', 'arang', 'shakan'],
		unawakenedName: 'Valkyrja',
		image: 'https://vignette.wikia.nocookie.net/summoners-war-sky-arena/images/5/54/Valkyrja_%28Wind%29_Icon.png/revision/latest/scale-to-width-down/85?cb=20141213080233'
	},
	xiongfei: {
		currentStars: 5,
		neededStars: 5,
		element: 'fire', 
		highEle: 20,
		midEle: 10,
		lowEle: 0,
		highMagic: 15,
		midMagic: 5,
		lowMagic: 0,
		requires: ['qebehsenuef', 'lingling', 'akia', 'geoffrey'],
		unawakenedName: 'Panda Warrior',
		image: 'https://vignette.wikia.nocookie.net/summoners-war-sky-arena/images/1/11/Panda_Warrior_%28Fire%29_Icon.png/revision/latest/scale-to-width-down/85?cb=20160428134955'
	},
	veromos: {
		currentStars: 5,
		neededStars: 5,
		element: 'dark', 
		highEle: 20,
		midEle: 10,
		lowEle: 0,
		highMagic: 15,
		midMagic: 5,
		lowMagic: 0,
		requires: ['argen', 'akia', 'mikene', 'kumae'],
		unawakenedName: 'Ifrit',
		image: 'https://vignette.wikia.nocookie.net/summoners-war-sky-arena/images/8/86/Ifrit_%28Dark%29_Icon.png/revision/latest/scale-to-width-down/85?cb=20150302141911'
	},
	//sigmarus: 'arang', 'jojo', 'susano', 'mina'
	arang: {
		currentStars: 4,
		neededStars: 5,
		element: 'wind', 
		highEle: 10,
		midEle: 20,
		lowEle: 0,
		highMagic: 5,
		midMagic: 15,
		lowMagic: 0,
		requires: ['prilea', 'hina', 'kahli', 'konamiya'],
		unawakenedName: 'Nine-tailed Fox',
		image: 'https://vignette.wikia.nocookie.net/summoners-war-sky-arena/images/6/67/Nine-tailed_Fox_%28Wind%29_Icon.png/revision/latest/scale-to-width-down/85?cb=20141213081313'
	},
	jojo: {
		currentStars: 4,
		neededStars: 5,
		element: 'fire', 
		highEle: 10,
		midEle: 20,
		lowEle: 0,
		highMagic: 5,
		midMagic: 15,
		lowMagic: 0,
		requires: ['garoche', 'cassandra', 'kuhn', 'chichi'],
		unawakenedName: 'Joker',
		image: 'https://vignette.wikia.nocookie.net/summoners-war-sky-arena/images/c/c9/Joker_%28Fire%29_Icon.png/revision/latest/scale-to-width-down/85?cb=20141213075507'
	},
	susano: {
		currentStars: 4,
		neededStars: 5,
		element: 'water', 
		highEle: 10,
		midEle: 20,
		lowEle: 0,
		highMagic: 5,
		midMagic: 15,
		lowMagic: 0,
		requires: ['icaru', 'kahn', 'dagorr', 'tantra'],
		unawakenedName: 'Ninja',
		image: 'https://vignette.wikia.nocookie.net/summoners-war-sky-arena/images/3/31/Ninja_%28Water%29_Icon.png/revision/latest/scale-to-width-down/85?cb=20141213080112'
	},
	mina: {
		currentStars: 3,
		neededStars: 5,
		element: 'water', 
		highEle: 0,
		midEle: 15,
		lowEle: 10,
		highMagic: 0,
		midMagic: 10,
		lowMagic: 5,
		requires: [], 
		unawakenedName: 'Martial Cat',
		image: 'https://vignette.wikia.nocookie.net/summoners-war-sky-arena/images/0/08/Martial_Cat_%28Water%29_Icon.png/revision/latest/scale-to-width-down/100?cb=20141213075146'
	},
	//katarina: ['baretta', 'mikene', 'arang', 'shakan']
	baretta: {
		currentStars: 4,
		neededStars: 5,
		element: 'fire', 
		highEle: 10,
		midEle: 20,
		lowEle: 0,
		highMagic: 5,
		midMagic: 15,
		lowMagic: 0,
		requires: ['fao', 'mei', 'sharron', 'lukan'],
		unawakenedName: 'Sylph',
		image: 'https://vignette.wikia.nocookie.net/summoners-war-sky-arena/images/d/de/Sylph_%28Fire%29_Icon.png/revision/latest/scale-to-width-down/85?cb=20141213080854'
	},
	mikene: {
		currentStars: 4,
		neededStars: 5,
		element: 'water', 
		highEle: 10,
		midEle: 20,
		lowEle: 0,
		highMagic: 5,
		midMagic: 15,
		lowMagic: 0,
		requires: ['gruda', 'hemos', 'anduril', 'cogma'],
		unawakenedName: 'Undine',
		image: 'https://vignette.wikia.nocookie.net/summoners-war-sky-arena/images/c/c6/Undine_%28Water%29_Icon.png/revision/latest/scale-to-width-down/85?cb=20170509105529'
	},
	shakan: {
		currentStars: 3,
		neededStars: 5,
		element: 'Wind', 
		highEle: 0,
		midEle: 15,
		lowEle: 10,
		highMagic: 0,
		midMagic: 10,
		lowMagic: 5,
		requires: [], 
		unawakenedName: 'Werewolf',
		image: 'https://vignette.wikia.nocookie.net/summoners-war-sky-arena/images/3/36/Werewolf_%28Wind%29_Icon.png/revision/latest/scale-to-width-down/100?cb=20141213075627'
	},
	//veromos: ['argen', 'akia', 'mikene', 'kumae']
	argen: {
		currentStars: 4,
		neededStars: 5,
		element: 'wind', 
		highEle: 12,
		midEle: 15,
		lowEle: 0,
		highMagic: 10,
		midMagic: 15,
		lowMagic: 0,
		requires: ['eintau', 'velfinodon', 'iron', 'kacey'],
		unawakenedName: 'Vampire',
		image: 'https://vignette.wikia.nocookie.net/summoners-war-sky-arena/images/c/ce/Vampire_%28Wind%29_Icon.png/revision/latest/scale-to-width-down/85?cb=20141213075620'
	},
	akia: {
		currentStars: 4,
		neededStars: 5,
		element: 'fire', 
		highEle: 10,
		midEle: 20,
		lowEle: 0,
		highMagic: 5,
		midMagic: 15,
		lowMagic: 0,
		requires: ['nangrim', 'krakdon', 'ramira', 'seal'],
		unawakenedName: 'Succubus',
		image: 'https://vignette.wikia.nocookie.net/summoners-war-sky-arena/images/8/84/Succubus_%28Fire%29_Icon.png/revision/latest/scale-to-width-down/85?cb=20141213080545'
	},
	kumae: {
		currentStars: 3,
		neededStars: 5,
		element: 'Fire', 
		highEle: 0,
		midEle: 0,
		lowEle: 20,
		highMagic: 0,
		midMagic: 1,
		lowMagic: 15,
		requires: [], 
		unawakenedName: 'Yeti',
		image: 'https://vignette.wikia.nocookie.net/summoners-war-sky-arena/images/4/4b/Yeti_%28Dark%29_Icon.png/revision/latest/scale-to-width-down/100?cb=20170509162156'
	},
	//xiongfei: ['qebehsenuef', 'lingling', 'akia', 'geoffrey']
	lingling: {
		currentStars: 4,
		neededStars: 5,
		element: 'wind', 
		highEle: 10,
		midEle: 20,
		lowEle: 0,
		highMagic: 5,
		midMagic: 15,
		lowMagic: 0,
		requires: ['hiva', 'zephicus', 'raoq', 'fynn'],
		unawakenedName: 'Kung Fu Girl',
		image: 'https://vignette.wikia.nocookie.net/summoners-war-sky-arena/images/7/78/Kung_Fu_Girl_%28Wind%29_Icon.png/revision/latest/scale-to-width-down/85?cb=20141213074250'
	},
	qebehsenuef: {
		currentStars: 4,
		neededStars: 5,
		element: 'water', 
		highEle: 12,
		midEle: 15,
		lowEle: 0,
		highMagic: 7,
		midMagic: 15,
		lowMagic: 0,
		requires: ['shailoq', 'nubia', 'ragion', 'sieq'],
		unawakenedName: 'Horus',
		image: 'https://vignette.wikia.nocookie.net/summoners-war-sky-arena/images/7/72/Horus_%28Water%29_Icon.png/revision/latest/scale-to-width-down/85?cb=20170503081835'
	},
	geoffrey: {
		currentStars: 3,
		neededStars: 5,
		element: 'fire', 
		highEle: 0,
		midEle: 5,
		lowEle: 15,
		highMagic: 0,
		midMagic: 5,
		lowMagic: 10,
		requires: [],
		unawakenedName: 'Viking',
		image: 'https://vignette.wikia.nocookie.net/summoners-war-sky-arena/images/1/1a/Viking_%28Fire%29_Icon.png/revision/latest/scale-to-width-down/100?cb=20141213075357'
	},
	//jeanne: ['kaz', 'lingling', 'harmonia', 'loren']
	kaz: {
		currentStars: 4,
		neededStars: 5,
		element: 'water', 
		highEle: 12,
		midEle: 15,
		lowEle: 0,
		highMagic: 7,
		midMagic: 15,
		lowMagic: 0,
		requires: ['shailoq', 'nubia', 'ragion', 'sieq'],
		unawakenedName: 'Samurai',
		image: 'https://vignette.wikia.nocookie.net/summoners-war-sky-arena/images/a/a7/Samurai_%28Water%29_Icon.png/revision/latest/scale-to-width-down/85?cb=20140929100003'
	},
	harmonia: {
		currentStars: 4,
		neededStars: 5,
		element: 'fire', 
		highEle: 12,
		midEle: 15,
		lowEle: 0,
		highMagic: 10,
		midMagic: 15,
		lowMagic: 0,
		requires: ['rebecca', 'kaien', 'dagora', 'aeilene'],
		unawakenedName: 'Harp Magician',
		image: 'https://vignette.wikia.nocookie.net/summoners-war-sky-arena/images/1/1d/Harp_Magician_%28Fire%29_Icon.png/revision/latest/scale-to-width-down/85?cb=20161130125457'
	},
	loren: {
		currentStars: 3,
		neededStars: 5,
		element: 'light', 
		highEle: 0,
		midEle: 15,
		lowEle: 10,
		highMagic: 0,
		midMagic: 10,
		lowMagic: 5,
		requires: [], 
		unawakenedName: 'Cow Girl',
		image: 'https://vignette.wikia.nocookie.net/summoners-war-sky-arena/images/5/52/Cow_Girl_%28Light%29_Icon.png/revision/latest/scale-to-width-down/100?cb=20150305165051'
	},
	//arang prilea hina kahli konamiya
	prilea: {
		currentStars: 3,
		neededStars: 4,
		element: 'wind', 
		highEle: 0,
		midEle: 15,
		lowEle: 10,
		highMagic: 0,
		midMagic: 10,
		lowMagic: 5,
		requires: [], 
		unawakenedName: 'Harpy',
		image: 'https://vignette.wikia.nocookie.net/summoners-war-sky-arena/images/0/01/Harpy_%28Wind%29_Icon.png/revision/latest/scale-to-width-down/100?cb=20141213081636'
	},
	hina: {
		currentStars: 3,
		neededStars: 4,
		element: 'wind', 
		highEle: 0,
		midEle: 15,
		lowEle: 10,
		highMagic: 0,
		midMagic: 10,
		lowMagic: 5,
		requires: [], 
		unawakenedName: 'Amazon',
		image: 'https://vignette.wikia.nocookie.net/summoners-war-sky-arena/images/7/7c/Amazon_%28Wind%29_Icon.png/revision/latest/scale-to-width-down/100?cb=20141213074922'
	},
	kahli: {
		currentStars: 3,
		neededStars: 4,
		element: 'fire', 
		highEle: 0,
		midEle: 15,
		lowEle: 10,
		highMagic: 0,
		midMagic: 10,
		lowMagic: 5,
		requires: [], 
		unawakenedName: 'High Elemental',
		image: 'https://vignette.wikia.nocookie.net/summoners-war-sky-arena/images/4/48/High_Elemental_%28Fire%29_Icon.png/revision/latest/scale-to-width-down/100?cb=20170503081110'
	},
	konamiya: {
		currentStars: 2,
		neededStars: 4,
		element: 'water', 
		highEle: 0,
		midEle: 2,
		lowEle: 15,
		highMagic: 0,
		midMagic: 0,
		lowMagic: 15,
		requires: [], 
		unawakenedName: 'Garuda',
		image: 'https://vignette.wikia.nocookie.net/summoners-war-sky-arena/images/7/70/Garuda_%28Water%29_Icon.png/revision/latest/scale-to-width-down/100?cb=20170501081343'
	},
	//jojo garoche cassandra kuhn chichi
	cassandra: {
		currentStars: 3,
		neededStars: 4,
		element: 'fire', 
		highEle: 0,
		midEle: 15,
		lowEle: 10,
		highMagic: 0,
		midMagic: 10,
		lowMagic: 5,
		requires: [], 
		unawakenedName: 'Magical Archer',
		image: 'https://vignette.wikia.nocookie.net/summoners-war-sky-arena/images/0/05/Magical_Archer_%28Fire%29_Icon.png/revision/latest/scale-to-width-down/100?cb=20141213075140'
	},
	kuhn: {
		currentStars: 3,
		neededStars: 4,
		element: 'water', 
		highEle: 0,
		midEle: 15,
		lowEle: 10,
		highMagic: 0,
		midMagic: 10,
		lowMagic: 5,
		requires: [], 
		unawakenedName: 'Golem',
		image: 'https://vignette.wikia.nocookie.net/summoners-war-sky-arena/images/7/7c/Golem_%28Water%29_Icon.png/revision/latest/scale-to-width-down/100?cb=20170501083424'
	},
	garoche: {
		currentStars: 3,
		neededStars: 4,
		element: 'fire', 
		highEle: 0,
		midEle: 15,
		lowEle: 10,
		highMagic: 0,
		midMagic: 10,
		lowMagic: 5,
		requires: [], 
		unawakenedName: 'Werewolf',
		image: 'https://vignette.wikia.nocookie.net/summoners-war-sky-arena/images/c/c5/Werewolf_%28Fire%29_Icon.png/revision/latest/scale-to-width-down/100?cb=20141213075626'
	},
	chichi: {
		currentStars: 2,
		neededStars: 4,
		element: 'wind', 
		highEle: 0,
		midEle: 0,
		lowEle: 20,
		highMagic: 0,
		midMagic: 0,
		lowMagic: 15,
		requires: [], 
		unawakenedName: 'Howl',
		image: 'https://vignette.wikia.nocookie.net/summoners-war-sky-arena/images/4/4a/Howl_%28Wind%29_Icon.png/revision/latest/scale-to-width-down/100?cb=20170503082659'
	},
	//susano icaru kahn dagorr tantra
	icaru: {
		currentStars: 3,
		neededStars: 4,
		element: 'water', 
		highEle: 0,
		midEle: 15,
		lowEle: 10,
		highMagic: 0,
		midMagic: 10,
		lowMagic: 5,
		requires: [], 
		unawakenedName: 'Inugami',
		image: 'https://vignette.wikia.nocookie.net/summoners-war-sky-arena/images/6/68/Inugami_%28Water%29_Icon.png/revision/latest/scale-to-width-down/100?cb=20170503083353'
	},
	kahn: {
		currentStars: 3,
		neededStars: 4,
		element: 'water', 
		highEle: 0,
		midEle: 15,
		lowEle: 10,
		highMagic: 0,
		midMagic: 10,
		lowMagic: 5,
		requires: [], 
		unawakenedName: 'Griffon',
		image: 'https://vignette.wikia.nocookie.net/summoners-war-sky-arena/images/4/43/Griffon_%28Water%29_Icon.png/revision/latest/scale-to-width-down/100?cb=20141213081149'
	},
	dagorr: {
		currentStars: 3,
		neededStars: 4,
		element: 'wind', 
		highEle: 0,
		midEle: 15,
		lowEle: 10,
		highMagic: 0,
		midMagic: 10,
		lowMagic: 5,
		requires: [], 
		unawakenedName: 'Bearman',
		image: 'https://vignette.wikia.nocookie.net/summoners-war-sky-arena/images/b/bb/Bearman_%28Wind%29_Icon.png/revision/latest/scale-to-width-down/100?cb=20141213075723'
	},
	tantra: {
		currentStars: 2,
		neededStars: 4,
		element: 'fire', 
		highEle: 0,
		midEle: 1,
		lowEle: 15,
		highMagic: 0,
		midMagic: 0,
		lowMagic: 15,
		requires: [], 
		unawakenedName: 'Yeti',
		image: 'https://vignette.wikia.nocookie.net/summoners-war-sky-arena/images/c/c6/Yeti_%28Fire%29_Icon.png/revision/latest/scale-to-width-down/100?cb=20170509161828'
	},
	//baretta fao mei sharron lukan
	fao: {
		currentStars: 3,
		neededStars: 4,
		element: 'fire', 
		highEle: 0,
		midEle: 15,
		lowEle: 10,
		highMagic: 0,
		midMagic: 10,
		lowMagic: 5,
		requires: [], 
		unawakenedName: 'Serpent',
		image: 'https://vignette.wikia.nocookie.net/summoners-war-sky-arena/images/7/78/Serpent_%28Fire%29_Icon.png/revision/latest/scale-to-width-down/100?cb=20170509103338'
	},
	mei: {
		currentStars: 3,
		neededStars: 4,
		element: 'fire', 
		highEle: 0,
		midEle: 15,
		lowEle: 10,
		highMagic: 0,
		midMagic: 10,
		lowMagic: 5,
		requires: [], 
		unawakenedName: 'Martial Cat',
		image: 'https://vignette.wikia.nocookie.net/summoners-war-sky-arena/images/d/d2/Martial_Cat_%28Fire%29_Icon.png/revision/latest/scale-to-width-down/100?cb=20141213075143'
	},
	sharron: {
		currentStars: 3,
		neededStars: 4,
		element: 'water', 
		highEle: 0,
		midEle: 20,
		lowEle: 5,
		highMagic: 0,
		midMagic: 20,
		lowMagic: 5,
		requires: [], 
		unawakenedName: 'Magical Archer',
		image: 'https://vignette.wikia.nocookie.net/summoners-war-sky-arena/images/f/f5/Magical_Archer_%28Water%29_Icon.png/revision/latest/scale-to-width-down/100?cb=20141213075141'
	},
	lukan: {
		currentStars: 2,
		neededStars: 4,
		element: 'wind', 
		highEle: 0,
		midEle: 0,
		lowEle: 20,
		highMagic: 0,
		midMagic: 2,
		lowMagic: 10,
		requires: [], 
		unawakenedName: 'Salamander',
		image: 'https://vignette.wikia.nocookie.net/summoners-war-sky-arena/images/b/b2/Salamander_%28Wind%29_Icon.png/revision/latest/scale-to-width-down/100?cb=20170508160353'
	},
	//mikene gruda hemos anduril cogma
	gruda: {
		currentStars: 3,
		neededStars: 4,
		element: 'water', 
		highEle: 0,
		midEle: 10,
		lowEle: 5,
		highMagic: 0,
		midMagic: 15,
		lowMagic: 10,
		requires: [], 
		unawakenedName: 'Bearman',
		image: 'https://vignette.wikia.nocookie.net/summoners-war-sky-arena/images/4/49/Bearman_%28Water%29_Icon.png/revision/latest/scale-to-width-down/100?cb=20141213075723'
	},
	hemos: {
		currentStars: 3,
		neededStars: 4,
		element: 'water', 
		highEle: 0,
		midEle: 15,
		lowEle: 10,
		highMagic: 0,
		midMagic: 10,
		lowMagic: 5,
		requires: [], 
		unawakenedName: 'Grim Reaper',
		image: 'https://vignette.wikia.nocookie.net/summoners-war-sky-arena/images/8/89/Grim_Reaper_%28Water%29_Icon.png/revision/latest/scale-to-width-down/100?cb=20141213075130'
	},
	anduril: {
		currentStars: 3,
		neededStars: 4,
		element: 'wind', 
		highEle: 0,
		midEle: 15,
		lowEle: 10,
		highMagic: 0,
		midMagic: 10,
		lowMagic: 5,
		requires: [], 
		unawakenedName: 'Inferno',
		image: 'https://vignette.wikia.nocookie.net/summoners-war-sky-arena/images/f/fc/Inferno_%28Wind%29_Icon.png/revision/latest/scale-to-width-down/100?cb=20141213080804'
	},
	cogma: {
		currentStars: 2,
		neededStars: 4,
		element: 'fire', 
		highEle: 0,
		midEle: 0,
		lowEle: 20,
		highMagic: 0,
		midMagic: 0,
		lowMagic: 15,
		requires: [],
		unawakenedName: 'Imp',
		image: 'https://vignette.wikia.nocookie.net/summoners-war-sky-arena/images/b/b1/Imp_%28Fire%29_Icon.png/revision/latest/scale-to-width-down/100?cb=20141213081638'
	},
	//argen eintau velfinodon iron kacey
	eintau: {
		currentStars: 3,
		neededStars: 4,
		element: 'wind', 
		highEle: 0,
		midEle: 15,
		lowEle: 10,
		highMagic: 0,
		midMagic: 10,
		lowMagic: 5,
		requires: [], 
		unawakenedName: 'Minotauros',
		image: 'https://vignette.wikia.nocookie.net/summoners-war-sky-arena/images/6/6a/Minotauros_%28Wind%29_Icon.png/revision/latest/scale-to-width-down/100?cb=20141028103240'
	},
	velfinodon: {
		currentStars: 3,
		neededStars: 4,
		element: 'wind', 
		highEle: 0,
		midEle: 15,
		lowEle: 10,
		highMagic: 0,
		midMagic: 10,
		lowMagic: 5,
		requires: [],
		unawakenedName: 'Lizardman',
		image: 'https://vignette.wikia.nocookie.net/summoners-war-sky-arena/images/9/96/Lizardman_%28Wind%29_Icon.png/revision/latest/scale-to-width-down/100?cb=20141028103435'
	},
	iron: {
		currentStars: 3,
		neededStars: 4,
		element: 'fire', 
		highEle: 0,
		midEle: 15,
		lowEle: 10,
		highMagic: 0,
		midMagic: 10,
		lowMagic: 5,
		requires: [], 
		unawakenedName: 'Living Armor',
		image: 'https://vignette.wikia.nocookie.net/summoners-war-sky-arena/images/1/12/Living_Armor_%28Fire%29_Icon.png/revision/latest/scale-to-width-down/100?cb=20141213074427'
	},
	kacey: {
		currentStars: 2,
		neededStars: 4,
		element: 'water', 
		highEle: 0,
		midEle: 2,
		lowEle: 15,
		highMagic: 0,
		midMagic: 0,
		lowMagic: 15,
		requires: [], 
		unawakenedName: 'Pixie',
		image: 'https://vignette.wikia.nocookie.net/summoners-war-sky-arena/images/7/79/Pixie_%28Water%29_Icon.png/revision/latest/scale-to-width-down/100?cb=20141213081742'
	},
	//akia nangrim krakdon ramira seal
	nangrim: {
		currentStars: 3,
		neededStars: 4,
		element: 'fire', 
		highEle: 0,
		midEle: 15,
		lowEle: 10,
		highMagic: 0,
		midMagic: 10,
		lowMagic: 5,
		requires: [], 
		unawakenedName: 'Beast Hunter',
		image: 'https://vignette.wikia.nocookie.net/summoners-war-sky-arena/images/5/56/Beast_Hunter_%28Fire%29_Icon.png/revision/latest/scale-to-width-down/100?cb=20170429121159'
	},
	krakdon: {
		currentStars: 3,
		neededStars: 4,
		element: 'fire', 
		highEle: 0,
		midEle: 2,
		lowEle: 10,
		highMagic: 0,
		midMagic: 0,
		lowMagic: 20,
		requires: [],
		unawakenedName: 'Salamander',
		image: 'https://vignette.wikia.nocookie.net/summoners-war-sky-arena/images/c/ca/Salamander_%28Fire%29_Icon.png/revision/latest/scale-to-width-down/100?cb=20170508155103'
	},
	ramira: {
		currentStars: 3,
		neededStars: 4,
		element: 'water', 
		highEle: 0,
		midEle: 15,
		lowEle: 10,
		highMagic: 0,
		midMagic: 10,
		lowMagic: 5,
		requires: [], 
		unawakenedName: 'Harpy',
		image: 'https://vignette.wikia.nocookie.net/summoners-war-sky-arena/images/a/a0/Harpy_%28Water%29_Icon.png/revision/latest/scale-to-width-down/100?cb=20141213081636'
	},
	seal: {
		currentStars: 2,
		neededStars: 4,
		element: 'wind', 
		highEle: 0,
		midEle: 5,
		lowEle: 15,
		highMagic: 0,
		midMagic: 5,
		lowMagic: 10,
		requires: [], 
		unawakenedName: 'Harpu',
		image: 'https://vignette.wikia.nocookie.net/summoners-war-sky-arena/images/a/a6/Harpu_%28Wind%29_Icon.png/revision/latest/scale-to-width-down/100?cb=20170503074947'
	},
	//lingling hiva zephicus raoq fynn
	hiva: {
		currentStars: 3,
		neededStars: 4,
		element: 'wind', 
		highEle: 0,
		midEle: 15,
		lowEle: 10,
		highMagic: 0,
		midMagic: 10,
		lowMagic: 5,
		requires: [], 
		unawakenedName: 'Grim Reaper',
		image: 'https://vignette.wikia.nocookie.net/summoners-war-sky-arena/images/6/63/Grim_Reaper_%28Wind%29_Icon.png/revision/latest/scale-to-width-down/100?cb=20141213075131'
	},
	zephicus: {
		currentStars: 3,
		neededStars: 4,
		element: 'wind', 
		highEle: 0,
		midEle: 15,
		lowEle: 10,
		highMagic: 0,
		midMagic: 10,
		lowMagic: 5,
		requires: [],
		unawakenedName: 'Charger Shark',
		image: 'https://vignette.wikia.nocookie.net/summoners-war-sky-arena/images/9/95/Charger_Shark_%28Wind%29_Icon.png/revision/latest/scale-to-width-down/100?cb=20150605215718'
	},
	raoq: {
		currentStars: 3,
		neededStars: 4,
		element: 'fire', 
		highEle: 0,
		midEle: 15,
		lowEle: 10,
		highMagic: 0,
		midMagic: 10,
		lowMagic: 5,
		requires: [],
		unawakenedName: 'Inugami',
		image: 'https://vignette.wikia.nocookie.net/summoners-war-sky-arena/images/0/04/Inugami_%28Fire%29_Icon.png/revision/latest/scale-to-width-down/100?cb=20170503083239' 
	},
	fynn: {
		currentStars: 2,
		neededStars: 4,
		element: 'water', 
		highEle: 0,
		midEle: 0,
		lowEle: 20,
		highMagic: 0,
		midMagic: 0,
		lowMagic: 15,
		requires: [], 
		unawakenedName: 'Imp',
		image: 'https://vignette.wikia.nocookie.net/summoners-war-sky-arena/images/7/70/Imp_%28Water%29_Icon.png/revision/latest/scale-to-width-down/100?cb=20141213081640'
	},
	//Qebehsenuef shailoq nubia ragion sieq
	shailoq: {
		currentStars: 3,
		neededStars: 4,
		element: 'water', 
		highEle: 0,
		midEle: 15,
		lowEle: 10,
		highMagic: 0,
		midMagic: 10,
		lowMagic: 5,
		requires: [], 
		unawakenedName: 'Serpent',
		image: 'https://vignette.wikia.nocookie.net/summoners-war-sky-arena/images/d/d4/Serpent_%28Water%29_Icon.png/revision/latest/scale-to-width-down/100?cb=20170509103650'
	},
	nubia: {
		currentStars: 3,
		neededStars: 4,
		element: 'water', 
		highEle: 0,
		midEle: 15,
		lowEle: 10,
		highMagic: 0,
		midMagic: 10,
		lowMagic: 5,
		requires: [], 
		unawakenedName: 'Mummy',
		image: 'https://vignette.wikia.nocookie.net/summoners-war-sky-arena/images/7/78/Mummy_%28Water%29_Icon.png/revision/latest/scale-to-width-down/100?cb=20151001073828'
	},
	ragion: {
		currentStars: 3,
		neededStars: 4,
		element: 'wind', 
		highEle: 0,
		midEle: 15,
		lowEle: 10,
		highMagic: 0,
		midMagic: 10,
		lowMagic: 5,
		requires: [], 
		unawakenedName: 'Golem',
		image: 'https://vignette.wikia.nocookie.net/summoners-war-sky-arena/images/c/ce/Golem_%28Wind%29_Icon.png/revision/latest/scale-to-width-down/100?cb=20170501083633'
	},
	sieq: {
		currentStars: 2,
		neededStars: 4,
		element: 'fire', 
		highEle: 0,
		midEle: 0,
		lowEle: 20,
		highMagic: 0,
		midMagic: 0,
		lowMagic: 15,
		requires: [], 
		unawakenedName: 'Hellhound',
		image: 'https://vignette.wikia.nocookie.net/summoners-war-sky-arena/images/b/bc/Hellhound_%28Fire%29_Icon.png/revision/latest/scale-to-width-down/100?cb=20170503075302'
	},
	//harmonia rebecca kaien dagora aeilene
	rebecca: {
		currentStars: 3,
		neededStars: 4,
		element: 'fire', 
		highEle: 0,
		midEle: 15,
		lowEle: 10,
		highMagic: 0,
		midMagic: 10,
		lowMagic: 5,
		requires: [], 
		unawakenedName: 'Mystic Witch',
		image: 'https://vignette.wikia.nocookie.net/summoners-war-sky-arena/images/c/cf/Mystic_Witch_%28Fire%29_Icon.png/revision/latest/scale-to-width-down/100?cb=20141213074700'
	},
	kaien: {
		currentStars: 3,
		neededStars: 4,
		element: 'fire', 
		highEle: 0,
		midEle: 5,
		lowEle: 10,
		highMagic: 0,
		midMagic: 10,
		lowMagic: 15,
		requires: [], 
		unawakenedName: 'Vagabond',
		image: 'https://vignette.wikia.nocookie.net/summoners-war-sky-arena/images/b/b3/Vagabond_%28Fire%29_Icon.png/revision/latest/scale-to-width-down/100?cb=20170509112907'
	},
	dagora: {
		currentStars: 3,
		neededStars: 4,
		element: 'water', 
		highEle: 0,
		midEle: 5,
		lowEle: 15,
		highMagic: 0,
		midMagic: 5,
		lowMagic: 10,
		requires: [], 
		unawakenedName: 'Warbear',
		image: 'https://vignette.wikia.nocookie.net/summoners-war-sky-arena/images/9/96/Warbear_%28Water%29_Icon.png/revision/latest/scale-to-width-down/100?cb=20170509153516'
	},
	aeilene: {
		currentStars: 2,
		neededStars: 4,
		element: 'wind', 
		highEle: 0,
		midEle: 5,
		lowEle: 10,
		highMagic: 0,
		midMagic: 10,
		lowMagic: 15,
		requires: [],
		unawakenedName: 'Fairy',
		image: 'https://vignette.wikia.nocookie.net/summoners-war-sky-arena/images/5/5f/Fairy_%28Wind%29_Icon.png/revision/latest/scale-to-width-down/100?cb=20170501080238' 
	},
	//kaz luan purian ardella bremis
	luan: {
		currentStars: 3,
		neededStars: 4,
		element: 'water', 
		highEle: 0,
		midEle: 15,
		lowEle: 10,
		highMagic: 0,
		midMagic: 10,
		lowMagic: 5,
		requires: [], 
		unawakenedName: 'Martial Artist',
		image: 'https://vignette.wikia.nocookie.net/summoners-war-sky-arena/images/f/f1/Martial_Artist_%28Water%29_Icon.png/revision/latest/scale-to-width-down/100?cb=20150730144240'
	},
	purian: {
		currentStars: 3,
		neededStars: 4,
		element: 'water', 
		highEle: 0,
		midEle: 15,
		lowEle: 10,
		highMagic: 0,
		midMagic: 10,
		lowMagic: 5,
		requires: [], 
		unawakenedName: 'Inferno',
		image: 'https://vignette.wikia.nocookie.net/summoners-war-sky-arena/images/7/7f/Inferno_%28Water%29_Icon.png/revision/latest/scale-to-width-down/100?cb=20141213080803'
	},
	ardella: {
		currentStars: 3,
		neededStars: 4,
		element: 'wind', 
		highEle: 0,
		midEle: 20,
		lowEle: 5,
		highMagic: 0,
		midMagic: 15,
		lowMagic: 5,
		requires: [], 
		unawakenedName: 'Magical Archer',
		image: 'https://vignette.wikia.nocookie.net/summoners-war-sky-arena/images/b/b3/Magical_Archer_%28Wind%29_Icon.png/revision/latest/scale-to-width-down/100?cb=20141213075141'
	},
	bremis: {
		currentStars: 2,
		neededStars: 4,
		element: 'fire', 
		highEle: 0,
		midEle: 5,
		lowEle: 15,
		highMagic: 0,
		midMagic: 5,
		lowMagic: 10,
		requires: [], 
		unawakenedName: 'Elemental',
		image: 'https://vignette.wikia.nocookie.net/summoners-war-sky-arena/images/d/db/Elemental_%28Fire%29_Icon.png/revision/latest/scale-to-width-down/100?cb=20170501075059'
	},
}