export monsters = {
	jeanne: {
		currentStars: 5,
		neededStars: 5,
		element: ''light'', 
		highEle: 20,
		midEle: 10,
		lowEle: 0,
		highMagic: 15,
		midMagic: 5,
		lowMagic: 0,
		requires: ['kaz', 'lingling', 'harmonia', 'loren'],
		unawakenedName: 'paladin'
	},
	sigmarus: {
		currentStars: 5,
		neededStars: 5,
		element: 'water', 
		highEle: 20,
		midEle: 10,
		lowEle: 0,
		highMagic: 15,
		midMagic: 5,
		lowMagic: 0,
		requires: ['arang', 'jojo', 'susano', 'mina'],
		unawakenedName: 'phoenix'
	},
	katarina: {
		currentStars: 5,
		neededStars: 5,
		element: 'wind', 
		highEle: 20,
		midEle: 10,
		lowEle: 0,
		highMagic: 15,
		midMagic: 5,
		lowMagic: 0,
		requires: ['baretta', 'mikene', 'arang', 'shakan'],
		unawakenedName: 'valkyrja'
	},
	xiongfei: {
		currentStars: 5,
		neededStars: 5,
		element: 'fire', 
		highEle: 20,
		midEle: 10,
		lowEle: 0,
		highMagic: 15,
		midMagic: 5,
		lowMagic: 0,
		requires: ['qebehsenuef', 'lingling', 'akia', 'geoffrey'],
		unawakenedName: 'panda'
	},
	veromos: {
		currentStars: 5,
		neededStars: 5,
		element: 'dark', 
		highEle: 20,
		midEle: 10,
		lowEle: 0,
		highMagic: 15,
		midMagic: 5,
		lowMagic: 0,
		requires: ['argen', 'akia', 'mikene', 'kumae'],
		unawakenedName: 'ifrit'
	},
	//sigmarus: 'arang', 'jojo', 'susano', 'mina'
	arang: {
		currentStars: 4,
		neededStars: 5,
		element: 'wind', 
		highEle: 10,
		midEle: 20,
		lowEle: 0,
		highMagic: 5,
		midMagic: 15,
		lowMagic: 0,
		requires: ['prilea', 'hina', 'kahli', 'konamiya'],
		unawakenedName: 'Nine-tailed Fox'
	},
	jojo: {
		currentStars: 4,
		neededStars: 5,
		element: 'fire', 
		highEle: 10,
		midEle: 20,
		lowEle: 0,
		highMagic: 5,
		midMagic: 15,
		lowMagic: 0,
		requires: ['garoche', 'cassandra', 'kuhn', 'chichi'],
		unawakenedName: 'Joker'
	},
	susano: {
		currentStars: 4,
		neededStars: 5,
		element: 'water', 
		highEle: 10,
		midEle: 20,
		lowEle: 0,
		highMagic: 5,
		midMagic: 15,
		lowMagic: 0,
		requires: ['icaru', 'kahn', 'dagorr', 'tantra'],
		unawakenedName: 'Ninja'
	},
	mina: {
		currentStars: 3,
		neededStars: 5,
		element: 'water', 
		highEle: 0,
		midEle: 15,
		lowEle: 10,
		highMagic: 0,
		midMagic: 10,
		lowMagic: 5,
		requires: [], 
		unawakenedName: 'Martial Cat'
	},
	//katarina: ['baretta', 'mikene', 'arang', 'shakan']
	baretta: {
		currentStars: 4,
		neededStars: 5,
		element: 'fire', 
		highEle: 10,
		midEle: 20,
		lowEle: 0,
		highMagic: 5,
		midMagic: 15,
		lowMagic: 0,
		requires: ['fao', 'mei', 'sharron', 'lukan'],
		unawakenedName: 'Sylph'
	},
	mikene: {
		currentStars: 4,
		neededStars: 5,
		element: 'water', 
		highEle: 10,
		midEle: 20,
		lowEle: 0,
		highMagic: 5,
		midMagic: 15,
		lowMagic: 0,
		requires: ['gruda', 'hemos', 'anduril', 'cogma'],
		unawakenedName: 'Undine'
	},
	shakan: {
		currentStars: 3,
		neededStars: 5,
		element: 'water', 
		highEle: 0,
		midEle: 15,
		lowEle: 10,
		highMagic: 0,
		midMagic: 10,
		lowMagic: 5,
		requires: [], 
		unawakenedName: 'Werewolf'
	},
	//veromos: ['argen', 'akia', 'mikene', 'kumae']
	argen: {
		currentStars: 4,
		neededStars: 5,
		element: 'wind', 
		highEle: 12,
		midEle: 15,
		lowEle: 0,
		highMagic: 10,
		midMagic: 15,
		lowMagic: 0,
		requires: ['eintau', 'velfinodon', 'iron', 'kacey'],
		unawakenedName: 'Vampire'
	},
	akia: {
		currentStars: 4,
		neededStars: 5,
		element: 'fire', 
		highEle: 10,
		midEle: 20,
		lowEle: 0,
		highMagic: 5,
		midMagic: 15,
		lowMagic: 0,
		requires: ['nangrim', 'krakdon', 'ramira', 'seal'],
		unawakenedName: 'Succubus'
	},
	kumae: {
		currentStars: 3,
		neededStars: 5,
		element: 'water', 
		highEle: 0,
		midEle: 0,
		lowEle: 20,
		highMagic: 0,
		midMagic: 1,
		lowMagic: 15,
		requires: [], 
		unawakenedName: 'Yeti'
	},
	//xiongfei: ['qebehsenuef', 'lingling', 'akia', 'geoffrey']
	lingling: {
		currentStars: 4,
		neededStars: 5,
		element: 'wind', 
		highEle: 10,
		midEle: 20,
		lowEle: 0,
		highMagic: 5,
		midMagic: 15,
		lowMagic: 0,
		requires: ['hiva', 'zephicus', 'raoq', 'fynn'],
		unawakenedName: 'Kung-Fu Girl'
	},
	qebehsenuef: {
		currentStars: 4,
		neededStars: 5,
		element: 'water', 
		highEle: 12,
		midEle: 15,
		lowEle: 0,
		highMagic: 7,
		midMagic: 15,
		lowMagic: 0,
		requires: ['shailoq', 'nubia', 'ragion', 'sieq'],
		unawakenedName: 'Horus'
	},
	geoffrey: {
		currentStars: 3,
		neededStars: 5,
		element: 'fire', 
		highEle: 0,
		midEle: 5,
		lowEle: 15,
		highMagic: 0,
		midMagic: 5,
		lowMagic: 10,
		requires: [],
		unawakenedName: 'Viking' 
	},
	//jeanne: ['kaz', 'lingling', 'harmonia', 'loren']
	kaz: {
		currentStars: 4,
		neededStars: 5,
		element: 'water', 
		highEle: 12,
		midEle: 15,
		lowEle: 0,
		highMagic: 7,
		midMagic: 15,
		lowMagic: 0,
		requires: ['shailoq', 'nubia', 'ragion', 'sieq'],
		unawakenedName: 'Samurai'
	},
	harmonia: {
		currentStars: 4,
		neededStars: 5,
		element: 'fire', 
		highEle: 12,
		midEle: 15,
		lowEle: 0,
		highMagic: 10,
		midMagic: 15,
		lowMagic: 0,
		requires: ['rebecca', 'kaien', 'dagora', 'aeilene'],
		unawakenedName: 'Harp Magician'
	},
	loren: {
		currentStars: 3,
		neededStars: 5,
		element: 'light', 
		highEle: 0,
		midEle: 15,
		lowEle: 10,
		highMagic: 0,
		midMagic: 10,
		lowMagic: 5,
		requires: [], 
		unawakenedName: 'Cow Girl'
	},
	//arang prilea hina kahli konamiya
	prilea: {
		currentStars: 3,
		neededStars: 4,
		element: 'wind', 
		highEle: 0,
		midEle: 15,
		lowEle: 10,
		highMagic: 0,
		midMagic: 10,
		lowMagic: 5,
		requires: [], 
		unawakenedName: 'Harpy'
	},
	hina: {
		currentStars: 3,
		neededStars: 4,
		element: 'wind', 
		highEle: 0,
		midEle: 15,
		lowEle: 10,
		highMagic: 0,
		midMagic: 10,
		lowMagic: 5,
		requires: [], 
		unawakenedName: 'Amazon'
	},
	kahli: {
		currentStars: 3,
		neededStars: 4,
		element: 'fire', 
		highEle: 0,
		midEle: 15,
		lowEle: 10,
		highMagic: 0,
		midMagic: 10,
		lowMagic: 5,
		requires: [], 
		unawakenedName: 'High Elemental'
	},
	konamiya: {
		currentStars: 2,
		neededStars: 4,
		element: 'water', 
		highEle: 0,
		midEle: 2,
		lowEle: 15,
		highMagic: 0,
		midMagic: 0,
		lowMagic: 15,
		requires: [], 
		unawakenedName: 'Garuda'
	},
	//jojo garoche cassandra kuhn chichi
	cassandra: {
		currentStars: 3,
		neededStars: 4,
		element: 'fire', 
		highEle: 0,
		midEle: 15,
		lowEle: 10,
		highMagic: 0,
		midMagic: 10,
		lowMagic: 5,
		requires: [], 
		unawakenedName: 'Magical Archer'
	},
	kuhn: {
		currentStars: 3,
		neededStars: 4,
		element: 'water', 
		highEle: 0,
		midEle: 15,
		lowEle: 10,
		highMagic: 0,
		midMagic: 10,
		lowMagic: 5,
		requires: [], 
		unawakenedName: 'Golem'
	},
	garoche: {
		currentStars: 3,
		neededStars: 4,
		element: 'fire', 
		highEle: 0,
		midEle: 15,
		lowEle: 10,
		highMagic: 0,
		midMagic: 10,
		lowMagic: 5,
		requires: [], 
		unawakenedName: 'Werewolf'
	},
	chichi: {
		currentStars: 2,
		neededStars: 4,
		element: 'wind', 
		highEle: 0,
		midEle: 0,
		lowEle: 20,
		highMagic: 0,
		midMagic: 0,
		lowMagic: 15,
		requires: [], 
		unawakenedName: 'Howl'
	},
	//susano icaru kahn dagorr tantra
	icaru: {
		currentStars: 3,
		neededStars: 4,
		element: 'water', 
		highEle: 0,
		midEle: 15,
		lowEle: 10,
		highMagic: 0,
		midMagic: 10,
		lowMagic: 5,
		requires: [], 
		unawakenedName: 'Inugami'
	},
	kahn: {
		currentStars: 3,
		neededStars: 4,
		element: 'water', 
		highEle: 0,
		midEle: 15,
		lowEle: 10,
		highMagic: 0,
		midMagic: 10,
		lowMagic: 5,
		requires: [], 
		unawakenedName: 'Griffon'
	},
	dagorr: {
		currentStars: 3,
		neededStars: 4,
		element: 'wind', 
		highEle: 0,
		midEle: 15,
		lowEle: 10,
		highMagic: 0,
		midMagic: 10,
		lowMagic: 5,
		requires: [], 
		unawakenedName: 'Bearman'
	},
	tantra: {
		currentStars: 2,
		neededStars: 4,
		element: 'fire', 
		highEle: 0,
		midEle: 1,
		lowEle: 15,
		highMagic: 0,
		midMagic: 0,
		lowMagic: 15,
		requires: [], 
		unawakenedName: 'Yeti'
	},
	//baretta fao mei sharron lukan
	fao: {
		currentStars: 3,
		neededStars: 4,
		element: 'fire', 
		highEle: 0,
		midEle: 15,
		lowEle: 10,
		highMagic: 0,
		midMagic: 10,
		lowMagic: 5,
		requires: [], 
		unawakenedName: 'Serpent'
	},
	mei: {
		currentStars: 3,
		neededStars: 4,
		element: 'fire', 
		highEle: 0,
		midEle: 15,
		lowEle: 10,
		highMagic: 0,
		midMagic: 10,
		lowMagic: 5,
		requires: [], 
		unawakenedName: 'Martial Cat'
	},
	sharron: {
		currentStars: 3,
		neededStars: 4,
		element: 'water', 
		highEle: 0,
		midEle: 20,
		lowEle: 5,
		highMagic: 0,
		midMagic: 20,
		lowMagic: 5,
		requires: [], 
		unawakenedName: 'Magical Archer'
	},
	lukan: {
		currentStars: 2,
		neededStars: 4,
		element: 'wind', 
		highEle: 0,
		midEle: 0,
		lowEle: 20,
		highMagic: 0,
		midMagic: 2,
		lowMagic: 10,
		requires: [], 
		unawakenedName: 'Salamander'
	},
	//mikene gruda hemos anduril cogma
	gruda: {
		currentStars: 3,
		neededStars: 4,
		element: 'water', 
		highEle: 0,
		midEle: 10,
		lowEle: 5,
		highMagic: 0,
		midMagic: 15,
		lowMagic: 10,
		requires: [], 
		unawakenedName: 'Bearman'
	},
	hemos: {
		currentStars: 3,
		neededStars: 4,
		element: 'water', 
		highEle: 0,
		midEle: 15,
		lowEle: 10,
		highMagic: 0,
		midMagic: 10,
		lowMagic: 5,
		requires: [], 
		unawakenedName: 'Grim Reaper'
	},
	anduril: {
		currentStars: 3,
		neededStars: 4,
		element: 'wind', 
		highEle: 0,
		midEle: 15,
		lowEle: 10,
		highMagic: 0,
		midMagic: 10,
		lowMagic: 5,
		requires: [], 
		unawakenedName: 'Inferno'
	},
	cogma: {
		currentStars: 2,
		neededStars: 4,
		element: 'fire', 
		highEle: 0,
		midEle: 0,
		lowEle: 20,
		highMagic: 0,
		midMagic: 0,
		lowMagic: 15,
		requires: [],
		unawakenedName: 'Imp' 
	},
	//argen eintau velfinodon iron kacey
	eintau: {
		currentStars: 3,
		neededStars: 4,
		element: 'wind', 
		highEle: 0,
		midEle: 15,
		lowEle: 10,
		highMagic: 0,
		midMagic: 10,
		lowMagic: 5,
		requires: [], 
		unawakenedName: 'Minotauros'
	},
	velfinodon: {
		currentStars: 3,
		neededStars: 4,
		element: 'wind', 
		highEle: 0,
		midEle: 15,
		lowEle: 10,
		highMagic: 0,
		midMagic: 10,
		lowMagic: 5,
		requires: [],
		unawakenedName: 'Lizardman' 
	},
	iron: {
		currentStars: 3,
		neededStars: 4,
		element: 'fire', 
		highEle: 0,
		midEle: 15,
		lowEle: 10,
		highMagic: 0,
		midMagic: 10,
		lowMagic: 5,
		requires: [], 
		unawakenedName: 'Living Armor'
	},
	kacey: {
		currentStars: 2,
		neededStars: 4,
		element: 'water', 
		highEle: 0,
		midEle: 2,
		lowEle: 15,
		highMagic: 0,
		midMagic: 0,
		lowMagic: 15,
		requires: [], 
		unawakenedName: 'Pixie'
	},
	//akia nangrim krakdon ramira seal
	nangrim: {
		currentStars: 3,
		neededStars: 4,
		element: 'fire', 
		highEle: 0,
		midEle: 15,
		lowEle: 10,
		highMagic: 0,
		midMagic: 10,
		lowMagic: 5,
		requires: [], 
		unawakenedName: 'Beast Hunter'
	},
	krakdon: {
		currentStars: 3,
		neededStars: 4,
		element: 'fire', 
		highEle: 0,
		midEle: 2,
		lowEle: 10,
		highMagic: 0,
		midMagic: 0,
		lowMagic: 20,
		requires: [],
		unawakenedName: 'Salamander' 
	},
	ramira: {
		currentStars: 3,
		neededStars: 4,
		element: 'water', 
		highEle: 0,
		midEle: 15,
		lowEle: 10,
		highMagic: 0,
		midMagic: 10,
		lowMagic: 5,
		requires: [], 
		unawakenedName: 'Harpy'
	},
	seal: {
		currentStars: 2,
		neededStars: 4,
		element: 'wind', 
		highEle: 0,
		midEle: 5,
		lowEle: 15,
		highMagic: 0,
		midMagic: 5,
		lowMagic: 10,
		requires: [], 
		unawakenedName: 'Harpu'
	},
	//lingling hiva zephicus raoq fynn
	hiva: {
		currentStars: 3,
		neededStars: 4,
		element: 'wind', 
		highEle: 0,
		midEle: 15,
		lowEle: 10,
		highMagic: 0,
		midMagic: 10,
		lowMagic: 5,
		requires: [], 
		unawakenedName: 'Grim Reaper'
	},
	zephicus: {
		currentStars: 3,
		neededStars: 4,
		element: 'wind', 
		highEle: 0,
		midEle: 15,
		lowEle: 10,
		highMagic: 0,
		midMagic: 10,
		lowMagic: 5,
		requires: [],
		unawakenedName: 'Charger Shark' 
	},
	raoq: {
		currentStars: 3,
		neededStars: 4,
		element: 'fire', 
		highEle: 0,
		midEle: 15,
		lowEle: 10,
		highMagic: 0,
		midMagic: 10,
		lowMagic: 5,
		requires: [],
		unawakenedName: 'Inugami' 
	},
	fynn: {
		currentStars: 2,
		neededStars: 4,
		element: 'water', 
		highEle: 0,
		midEle: 0,
		lowEle: 20,
		highMagic: 0,
		midMagic: 0,
		lowMagic: 15,
		requires: [], 
		unawakenedName: 'Imp'
	},
	//Qebehsenuef shailoq nubia ragion sieq
	shailoq: {
		currentStars: 3,
		neededStars: 4,
		element: 'water', 
		highEle: 0,
		midEle: 15,
		lowEle: 10,
		highMagic: 0,
		midMagic: 10,
		lowMagic: 5,
		requires: [], 
		unawakenedName: 'Serpent'
	},
	nubia: {
		currentStars: 3,
		neededStars: 4,
		element: 'water', 
		highEle: 0,
		midEle: 15,
		lowEle: 10,
		highMagic: 0,
		midMagic: 10,
		lowMagic: 5,
		requires: [], 
		unawakenedName: 'Mummy'
	},
	ragion: {
		currentStars: 3,
		neededStars: 4,
		element: 'wind', 
		highEle: 0,
		midEle: 15,
		lowEle: 10,
		highMagic: 0,
		midMagic: 10,
		lowMagic: 5,
		requires: [], 
		unawakenedName: 'Golem'
	},
	sieq: {
		currentStars: 2,
		neededStars: 4,
		element: 'fire', 
		highEle: 0,
		midEle: 0,
		lowEle: 20,
		highMagic: 0,
		midMagic: 0,
		lowMagic: 15,
		requires: [], 
		unawakenedName: 'Hellhound'
	},
	//harmonia rebecca kaien dagora aeilene
	rebecca: {
		currentStars: 3,
		neededStars: 4,
		element: 'fire', 
		highEle: 0,
		midEle: 15,
		lowEle: 10,
		highMagic: 0,
		midMagic: 10,
		lowMagic: 5,
		requires: [], 
		unawakenedName: 'Mystic Witch'
	},
	kaien: {
		currentStars: 3,
		neededStars: 4,
		element: 'fire', 
		highEle: 0,
		midEle: 5,
		lowEle: 10,
		highMagic: 0,
		midMagic: 10,
		lowMagic: 15,
		requires: [], 
		unawakenedName: 'Vagabond'
	},
	dagora: {
		currentStars: 3,
		neededStars: 4,
		element: 'water', 
		highEle: 0,
		midEle: 5,
		lowEle: 15,
		highMagic: 0,
		midMagic: 5,
		lowMagic: 10,
		requires: [], 
		unawakenedName: 'Warbear'
	},
	aeilene: {
		currentStars: 2,
		neededStars: 4,
		element: 'wind', 
		highEle: 0,
		midEle: 5,
		lowEle: 10,
		highMagic: 0,
		midMagic: 10,
		lowMagic: 15,
		requires: [],
		unawakenedName: 'Fairy' 
	},
	//kaz luan purian ardella bremis
	luan: {
		currentStars: 3,
		neededStars: 4,
		element: 'water', 
		highEle: 0,
		midEle: 15,
		lowEle: 10,
		highMagic: 0,
		midMagic: 10,
		lowMagic: 5,
		requires: [], 
		unawakenedName: 'Martial Artist'
	},
	purian: {
		currentStars: 3,
		neededStars: 4,
		element: 'water', 
		highEle: 0,
		midEle: 15,
		lowEle: 10,
		highMagic: 0,
		midMagic: 10,
		lowMagic: 5,
		requires: [], 
		unawakenedName: 'Inferno'
	},
	ardella: {
		currentStars: 3,
		neededStars: 4,
		element: 'wind', 
		highEle: 0,
		midEle: 20,
		lowEle: 5,
		highMagic: 0,
		midMagic: 15,
		lowMagic: 5,
		requires: [], 
		unawakenedName: 'Magical Archer'
	},
	bremis: {
		currentStars: 2,
		neededStars: 4,
		element: 'fire', 
		highEle: 0,
		midEle: 5,
		lowEle: 15,
		highMagic: 0,
		midMagic: 5,
		lowMagic: 10,
		requires: [], 
		unawakenedName: 'Elemental'
	},
}